### ISSUE TITLE
Define an "open browser" recognizer class

### ISSUE THREAD

**Issue by kimmrz** [009-Personal-Alexa-like-Speech-Service/009---Personal-Alexa-like-Speech-Service#10]
We started to interpret easy commands like simple questions (e.g. "How are you Hal?")

Now we want to implement a command to open a browser if the user uses the words "open browser"

**Comment by Max123S** [comment]
This library can probably work with URLs https://docs.python.org/3/library/urllib.html

**Comment by Max123S** [comment]
I closed the issue. We did not finish it but it is a possible future development.
