### ISSUE TITLE
Define wrong input

### ISSUE THREAD

**Issue by kimmrz** [009-Personal-Alexa-like-Speech-Service/009---Personal-Alexa-like-Speech-Service#12]
e. g. the backround noise it too loud or Hal doesnt understand the spoken command -> implement a sentences like "I didnt understand, please be clear mate"

**Comment by Max123S** [comment]
Do we agree on "error: Missing spoken words"? @kimmrz @Melina-MLEAN

**Comment by kimmrz** [comment]
Yes sounds good

**Comment by kimmrz** [comment]
I'll remove the issue to done
