### ISSUE TITLE
Install Spacy 

### ISSUE THREAD

**Issue by Max123S** [009-Personal-Alexa-like-Speech-Service/009---Personal-Alexa-like-Speech-Service#15]
@kimmrz @Melina-MLEAN

**Comment by Melina-MLEAN** [comment]
Install and add the code to our project - code folder: Interpreter

**Comment by kimmrz** [comment]
The installation didnt work. What about you?

**Comment by Max123S** [comment]
Try to type in "pip install -U spacy" in your terminal

**Comment by Max123S** [comment]
After that type in "python -m spacy download en_core_web_sm" in your terminal

**Comment by kimmrz** [comment]
Thank you Max! 
I added the "starter code" from Spacy and it worked

**Comment by kimmrz** [comment]
@Melina-MLEAN Did the installation work?

**Comment by Melina-MLEAN** [comment]
@kimmrz Yes, it worked!

**Comment by kimmrz** [comment]
Should we add that to our readme?

**Comment by kimmrz** [comment]
thanks for fixing that Max :D

**Comment by kimmrz** [comment]
python -m spacy download en_core_web_sm

**Comment by kimmrz** [comment]
We have a problem: spacy is installed but it doesnt work

**Comment by kimmrz** [comment]
pip install -U pip setuptools wheelpip install -U spacypython -m spacy download en_core_web_sm --> in terminal
