### ISSUE TITLE
Text processing

### ISSUE THREAD

**Issue by Melina-MLEAN** [009-Personal-Alexa-like-Speech-Service/009---Personal-Alexa-like-Speech-Service#16]
- write a routine, which removes all punctuation 
- split the spelled text (split function) and add punctuation
- keywords (instring-function) --> how to check if a substring is contained in a string
- keywords should recognize literal sense or a question

**Comment by kimmrz** [comment]
https://course.spacy.io/en/chapter1

**Comment by Melina-MLEAN** [comment]
https://spacy.io/usage/spacy-101 --> to understand how it works

**Comment by kimmrz** [comment]
https://melaniewalsh.github.io/Intro-Cultural-Analytics/features/Text-Analysis/POS-Keywords.html maybe we can use this code as well?

**Comment by kimmrz** [comment]
to do: 

different sentences for "What is your name?" 
and so on

**Comment by kimmrz** [comment]
- recognize city names 
- values for tokes.pos --> which values? 

Names entities:

- Hal can recognize different nouns
- e.g. a company name "Apple" --> "I dont like this company" 


create action: 

- def class recognizer --> different classes for recognizing
