### ISSUE TITLE
Explain spaCy's processing Pipeline (readme) 

### ISSUE THREAD

**Issue by kimmrz** [009-Personal-Alexa-like-Speech-Service/009---Personal-Alexa-like-Speech-Service#17]
I founds a website which explains the processing pipeline quite good. Maybe we can use that one for our readme-explanation 

https://www.analyticsvidhya.com/blog/2020/03/spacy-tutorial-learn-natural-language-processing/

**Comment by kimmrz** [comment]
https://analyticsindiamag.com/nlp-deep-learning-nlp-framework-nlp-model/

**Comment by Max123S** [comment]
I'll take care of it

**Comment by Max123S** [comment]
Finished. The images are still missing.
Can you tell me how to insert the pictures?

**Comment by Melina-MLEAN** [comment]
> Finished. The images are still missing.
> Can you tell me how to insert the pictures?

I added the images. 👍 
Maybe we should add it to --> 2) Methological approach?

**Comment by kimmrz** [comment]
Yes I moved it to methological approach. Thanks @Max123S :)

**Comment by kimmrz** [comment]
https://spacy.io/usage/models here's a good explanation for the command _nlp = spacy.load("en_core_web_sm")_
