### ISSUE TITLE
New class for time

### ISSUE THREAD

**Issue by kimmrz** [009-Personal-Alexa-like-Speech-Service/009---Personal-Alexa-like-Speech-Service#23]
We want to implement a new recognizer class regarding time. 

Example:
"Hello Hal, what time is it?"

answer: "Hi Dave, it's 02:26 pm"

**Comment by Max123S** [comment]
Maybe this library can help https://docs.python.org/3/library/datetime.html

**Comment by kimmrz** [comment]
```
import time

epoch_time = 1586944173.957986
local_time = time.ctime(epoch_time)

print("The local time is:", local_time)
```

**Comment by kimmrz** [comment]
https://careerkarma.com/blog/python-time/

**Comment by kimmrz** [comment]
Maybe we can try this code on friday 😄

**Comment by kimmrz** [comment]
In our session with Herr Zeutschler on Tuesday we managed to implement a class for time
