### ISSUE TITLE
Define all classes 

### ISSUE THREAD

**Issue by kimmrz** [009-Personal-Alexa-like-Speech-Service/009---Personal-Alexa-like-Speech-Service#28]
e. g. "Recognizes named entities like people names, city names etc."

**Comment by kimmrz** [comment]
define an "__init__" function for every class

**Comment by kimmrz** [comment]
class 1-5 Melina
class 6-10 Max 
class 11-end Kim

**Comment by Melina-MLEAN** [comment]
I finished the description for the last few classes and pushed the newest code to github.
