### ISSUE TITLE
Read me specify Business Problem (CRISP DM) 

### ISSUE THREAD

**Issue by kimmrz** [009-Personal-Alexa-like-Speech-Service/009---Personal-Alexa-like-Speech-Service#5]
1.1 Determine Business Objectives
Background.
Business Objectives. Business Success Criteria.
1.2 Assess Situation
Inventory of Resources, Requirements, Assumptions and Constraints.
Risks and Contingencies Terminology. Costs and Benefits.
1.3 Determine Data Mining Goals
Data Mining Goals.
Data Mining Success Criteria.
1.4 Produce Project Plan
Project Plan.
Initial Assessment of Tools and Techniques.

**Comment by Melina-MLEAN** [comment]
Done but I  still need to do 1.4

**Comment by kimmrz** [comment]
Do you know if it is possible to make the crip dm illustration a bit smaller?

**Comment by kimmrz** [comment]
I added a smaller crisp dm illustration

**Comment by Melina-MLEAN** [comment]
I added the task to our reed me ..maybe we could talk about the visualization for 1.4
