### ISSUE TITLE
get an overview about Spacy library

### ISSUE THREAD

**Issue by kimmrz** [009-Personal-Alexa-like-Speech-Service/009---Personal-Alexa-like-Speech-Service#7]
Which functions do "spacy" have? 
How can we use there for our use case?

**Comment by Max123S** [comment]
Spacy library is using machine learning to process language. So Hal can identify the meaning of a statement, even if its not exactly what we defined in the interpreter.

**Comment by Max123S** [comment]
https://spacy.io/usage/spacy-101 as an intro
