### ISSUE TITLE
develop a recorder with speech recognition 

### ISSUE THREAD

**Issue by kimmrz** [009-Personal-Alexa-like-Speech-Service/009---Personal-Alexa-like-Speech-Service#9]
I already installed the speech recognition library. The next step is to develop the code in our recorder

**Comment by Max123S** [comment]
Installed speech recognition. Qhen importing you have to write speech_recognition.

**Comment by kimmrz** [comment]
for now the recording doesn't work. What about you Max and Melina?

**Comment by Max123S** [comment]
Its working after the last session
